export const error = {
  NOT_LOGIN_ERROR: '로그인이 필요한 서비스입니다.',
  JWT_TOKEN_INVALID_ERROR: '더 이상 유효하지 않은 토큰입니다.',
  INCORRECT_ID_ERROR: '존재하지 않는 유저입니다.',
  INCORRECT_PWD_ERROR: '비밀번호를 다시 한 번 확인해주세요.',
  CHECK_ID_ERROR: '중복된 ID가 존재합니다.',
  LOGOUT_ERROR: '로그아웃에 실패하였습니다.',
  COMMON_ERROR: '처리 과정 중 에러가 발생했습니다',
  GET_LABEL_ERROR: '레이블 정보를 가져오는데 실패하였습니다.',
  GET_LABEL_LENGTH_ERROR: '레이블 개수를 가져오는데 실패하였습니다.',
  CREATE_LABEL_ERROR: '이미 존재하는 레이블입니다.',
  UPDATE_LABEL_ERROR: '레이블을 수정하는데 에러가 발생했습니다',
  DELETE_LABEL_ERROR: '레이블을 삭제하는데 에러가 발생했습니다',
  GET_ISSUE_FITLER_ERROR: '이슈 필터를 가져오는데 실패하였습니다.',
  GET_COMMENT_ERROR: '댓글 목록을 가져오는데 실패하였습니다.',
  CREATE_COMMENT_ERROR: '댓글을 게시하는데 실패하였습니다.',
  DELETE_COMMENT_ERROR: '댓글를 삭제하는데 실패하였습니다.',
  GET_BOARD_ERROR: '게시물을 가져오는데 에러가 발생했습니다',
  CREATE_IMAGE_ERROR: '이미지를 추가하는데 에러가 발생했습니다',
  CREATE_BOARD_ERROR: '게시글을 추가하는데 에러가 발생했습니다',
  UPDATE_BOARD_ERROR: '게시글을 수정하는데 에러가 발생했습니다',
  DELETE_BOARD_ERROR: '게시글을 삭제하는데 에러가 발생했습니다',
};
