export const error = {
  NOT_LOGIN_ERROR: '로그인이 필요한 서비스입니다.',
  INCORRECT_ID_ERROR: '존재하지 않는 유저입니다.',
  INCORRECT_PWD_ERROR: '비밀번호를 다시 한 번 확인해주세요.',
  CHECK_ID_ERROR: '중복된 ID가 존재합니다.',
  LOGOUT_ERROR: '로그아웃에 실패하였습니다.',
  COMMON_ERROR: '처리 과정 중 에러가 발생했습니다',
  GET_USERS_ERROR: '유저 목록을 가져오는데 실패하였습니다.',
  GET_USER_IMAGE_ERROR: '유저 이미지를 가져오는데 실패하였습니다.',
  GET_LABEL_ERROR: '레이블 정보를 가져오는데 실패하였습니다.',
  GET_LABEL_LENGTH_ERROR: '레이블 개수를 가져오는데 실패하였습니다.',
  CREATE_LABEL_ERROR: '이미 존재하는 레이블이 있습니다.',
  UPDATE_LABEL_ERROR: '이미 존재하는 레이블이 있습니다.',
  DELETE_LABEL_ERROR: '레이블을 삭제하는데 에러가 발생했습니다',
  GET_ISSUE_FILTER_ERROR: '이슈 필터를 가져오는데 실패하였습니다.',
  CREATE_ISSUE_FILTER_ERROR: '이슈 필터를 만드는데 실패하였습니다.',
  GET_COMMENT_ERROR: '댓글 목록을 가져오는데 실패하였습니다.',
  CREATE_COMMENT_ERROR: '댓글을 게시하는데 실패하였습니다.',
  DELETE_COMMENT_ERROR: '댓글를 삭제하는데 실패하였습니다.',
  GET_ISSUE_ERROR: '이슈를 가져오는데 실패하였습니다.',
  GET_ISSUE_LENGTH_ERROR: '이슈 개수를 가져오는데 실패하였습니다.',
  CREATE_IMAGE_ERROR: '이미지를 추가하는데 실패하였습니다.',
  CREATE_ISSUE_ERROR: '이슈를 추가하는데 실패하였습니다.',
  UPDATE_ISSUE_ERROR: '이슈를 수정하는데 실패하였습니다.',
  DELETE_ISSUE_ERROR: '이슈를 삭제하는데 실패하였습니다.',
};
